### ISSUE TITLE
"Could not parse brain configuration" error when launching the experiment

### ISSUE THREAD

**Issue by DennisZemela** [EduardoRosLab/VOR_in_neurorobotics#1]
Hello Eduardo,

I followed the configuration of the NRP for the iCub_VOR_UGR experiment.

However, when I launch the experiment, i get the following error:

Error Type: rospy.ServiceException

Error Code: -1

Message: Error starting the simulation. ("service [/ros_cle_simulation/create_new_simulation] responded with an error: error processing request: Could not parse brain configuration /tmp/nrp-simulation-dir/bibi_configuration.bibi due to validation error: (<class 'hbp_nrp_commons.generated.bibi_api_gen.SDFWithPath'>, <pyxb.namespace.ExpandedName object at 0x7f1bac055590>, <hbp_nrp_commons.generated.bibi_api_gen.SDFWithPath object at 0x7f1bac0552d0>, pyxb.utils.utility.Location(None, 24, 2))") (host: 172.19.0.3)

Data: service [/ros_cle_simulation/create_new_simulation] responded with an error: error processing request: Could not parse brain configuration /tmp/nrp-simulation-dir/bibi_configuration.bibi due to validation error: (<class 'hbp_nrp_commons.generated.bibi_api_gen.SDFWithPath'>, <pyxb.namespace.ExpandedName object at 0x7f1bac055590>, <hbp_nrp_commons.generated.bibi_api_gen.SDFWithPath object at 0x7f1bac0552d0>, pyxb.utils.utility.Location(None, 24, 2))

Stack Trace: l@http://localhost:9000/scripts/vendor.ef3aaf39.js:74:17993
error@http://localhost:9000/scripts/vendor.ef3aaf39.js:74:19141
controller@http://localhost:9000/scripts/vendor.ef3aaf39.js:75:954
g@http://localhost:9000/scripts/vendor.ef3aaf39.js:4:23528
vb/this.$get</</<@http://localhost:9000/scripts/vendor.ef3aaf39.js:5:18248
a.$get</j.open/k<@http://localhost:9000/scripts/vendor.ef3aaf39.js:70:11732
h@http://localhost:9000/scripts/vendor.ef3aaf39.js:6:8174
i/<@http://localhost:9000/scripts/vendor.ef3aaf39.js:6:8346
$eval@http://localhost:9000/scripts/vendor.ef3aaf39.js:6:15829
$digest@http://localhost:9000/scripts/vendor.ef3aaf39.js:6:14302
$apply@http://localhost:9000/scripts/vendor.ef3aaf39.js:6:16112
i@http://localhost:9000/scripts/vendor.ef3aaf39.js:5:22536
u@http://localhost:9000/scripts/vendor.ef3aaf39.js:5:24464
Kb/</x.onload@http://localhost:9000/scripts/vendor.ef3aaf39.js:5:24937

I already reinstalled the NRP again, hoping that this would solve the issue, but the same error remained. Nevertheless, I can open different Templates like the "Holodeck iCub Visual Tracking experiment" without issues.

Do you know how to solve this problem?

Thank you
Dennis

**Comment by FranciscoNaveros** [comment]
Hello Dennis.

Which NRP version are you using?. A local version from sources or from docker?. 

How did you create the new experiment and upload all the files included in this repository to this project?.

Maybe there are some probleme with the new NRP version.

Francisco.

**Comment by DennisZemela** [comment]
Hello Francisco.

Thank you for your fast reply.

I am using the NRP version from docker (docker version 18.09.7).

I created the experiment on localhost:9000/#/esv-private with these steps:

New experiment -> e.g.: Holodeck -> Name: "new" and Launch -> Stop and Exit the simulation

My experiments -> "new" -> Files -> Experiment files: template_new_0 -> Upload file -> all data from VOR_in_neurorobotics 

My experiments -> iCub VOR UGR -> Launch 



Dennis

**Comment by FranciscoNaveros** [comment]
Hello Dennis.

Did you follow the README instructions and upgrade the pynn version in the backend? --> (Upgrade the pyNN version in the backend:./nrp_installer connect_backend; pip install --upgrade pyNN).

*** I'm not sure if this upgrade of pynn version must be done in the backend or in the frontend. ***. The steps are basically the same --> (Upgrade the pyNN version in the frontend:./nrp_installer connect_frontend; pip install --upgrade pyNN).

Francisco.

**Comment by DennisZemela** [comment]
Hello Francisco

Indeed I followed the README instructions. The result for doing the upgrades in the frontend or the backend was the same:

dennis@dennis-XPS-13-9380:~$ ./nrp_installer.sh connect_backend; pip install --upgrade pyNN
Checking for script updates
nrp_installer.sh is up-to-date.
Opening new terminal into nrp container

Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
Use “-- ” to terminate the options and put the command line to execute after it.

DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already up-to-date: pyNN in ./.local/lib/python2.7/site-packages (0.9.4)
Requirement already satisfied, skipping upgrade: neo>=0.5.2 in ./.local/lib/python2.7/site-packages (from pyNN) (0.7.1)
Requirement already satisfied, skipping upgrade: lazyarray>=0.3.2 in ./.local/lib/python2.7/site-packages (from pyNN) (0.3.3)
Requirement already satisfied, skipping upgrade: numpy>=1.8.2 in /usr/lib/python2.7/dist-packages (from pyNN) (1.13.3)
Requirement already satisfied, skipping upgrade: quantities>=0.12.1 in ./.local/lib/python2.7/site-packages (from pyNN) (0.12.3)

Dennis

**Comment by FranciscoNaveros** [comment]
Hello Dennis.

I have tested this code in my computer. In my old NRP version, this project worked perfectly. Nevertheless, in the last NRP version, it does not work. I will try to solve this problem as soon as possible.

Francisco.

**Comment by FranciscoNaveros** [comment]
Hello Dennis.

I have fixed the problem. The new version should work properly in the new NRP version.

Francisco.
